# Generated by Django 4.0.6 on 2022-07-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('basics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pm',
            name='responsible_group',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
